name: Build Android 2

run-name: ${{ github.actor }} is testing out GitHub Actions 1 🚀
on: [push]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Android App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"
      
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        id: install_code
        run: npm install

      - name: Build app
        run: npm run build
      - name: Cap sync
        run: npx capacitor sync android 
      - name: Extract Android signing key from env
        run: |
          echo "${{ secrets.RELEASE_KEYSTORE }}" > android/release.jks.base64
          base64 -d android/release.jks.base64 > android/release.decrypted.jks
      - name: Bump Version
        uses: chkfung/android-version-actions@v1.2.2
        with:
          gradlePath: android/app/build.gradle
          versionCode: ${{ github.run_number }}
          versionName: 1.0.0
      - name: Build AAB and Sign
        run: npx cap build android --keystorepath release.decrypted.jks --keystorepass "${{ secrets.RELEASE_KEYSTORE_PASSWORD }}" --keystorealias "${{ secrets.RELEASE_KEY_ALIAS }}" --keystorealiaspass "${{ secrets.RELEASE_KEYSTORE_PASSWORD }}" --androidreleasetype AAB 
      - name: Upload AAB
        uses: actions/upload-artifact@v3
        with:
          name: app-release-signed.aab
          path: android/app/build/outputs/bundle/release
      - run: echo Build status report=${{ job.status }}
  deploy:
    name: Deploy Android
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download AAB
        uses: actions/download-artifact@v3
        with:
          name: app-release-signed.aab
      - name: Publish to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: '${{ secrets.SERVICE_JSON }}'
          packageName: com.testionic.fin.dmitry
          releaseFiles: '${{ github.workspace }}/app-release-signed.aab'
          track: internal

          


      
