name: Build Android

on:
  push:
    branches:
      - feat/actions

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"
      
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        id: install_code
        run: npm ci

      - name: Build app bundle 1
        run: npx capacitor update && npx capacitor build android
      - name: Build app bundle 2
        run: ls
        

      # - name: Extract Android signing key from env
      #   run: |
      #     echo "${{ secrets.RELEASE_KEYSTORE }}" > android/release.jks.base64
      #     base64 -d android/release.jks.base64 > android/release.decrypted.jks

      # - name: Sign dev build
      #   run: jarsigner -keystore android/release.decrypted.jks -storepass "${{ secrets.RELEASE_KEYSTORE_PASSWORD }}" -signedjar ./android/app/build/outputs/bundle/release/app-release-signed.aab ./android/app/build/outputs/bundle/release/app-release.aab release

      # - name: Check folder content of android output
      #   run: ls ./android/app/build/outputs/bundle/release

      # # - name: Upload release bundle
      # #   uses: actions/upload-artifact@v3
      # #   with:
      # #     name: app-release
      # #     path: ./android/app/build/outputs/bundle/release/app-release-signed.aab
      # #     retention-days: 60

      # - name: Set Tag
      #   id: current-datetime
      #   run: echo "CURRENT_DATETIME=$(date +'%Y-%m-%d-%H_%M_%S%z')" >> "$GITHUB_OUTPUT"

      # - name: Build Release
      #   shell: bash
      #   run: |
      #     hub release create ${{ steps.current-datetime.outputs.CURRENT_DATETIME }} \
      #     -m ${{ steps.current-datetime.outputs.CURRENT_DATETIME }} \
      #     -a ./android/app/build/outputs/bundle/release/app-release-signed.aab \
      #     -a ./android/app/build/outputs/apk/debug/app-debug.apk
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
